//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
            this.DoiTraHangHoas = new HashSet<DoiTraHangHoa>();
        }
    
        public System.Guid HoaDonId { get; set; }
        public long KhachHangId { get; set; }
        public long NhanVienId { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<long> NguoiChinhSuaId { get; set; }
        public Nullable<bool> HoatDong { get; set; }
    
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual ICollection<DoiTraHangHoa> DoiTraHangHoas { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
