//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.CT_XuatKho = new HashSet<CT_XuatKho>();
            this.DonHangs = new HashSet<DonHang>();
            this.HangHoas = new HashSet<HangHoa>();
        }
    
        public long Id { get; set; }
        public string TenNhaCungCap { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<long> NguoiTaoId { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<long> NguoiChinhSuaId { get; set; }
        public Nullable<bool> HoatDong { get; set; }
    
        public virtual ICollection<CT_XuatKho> CT_XuatKho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}
