//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKho
    {
        public NhapKho()
        {
            this.CT_NhapKho = new HashSet<CT_NhapKho>();
        }
    
        public System.Guid PhieuNhapKhoId { get; set; }
        public System.Guid DonHangId { get; set; }
        public long KhoId { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public long NhanVienId { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<long> NguoiChinhSuaId { get; set; }
        public Nullable<bool> HoatDong { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ICollection<CT_NhapKho> CT_NhapKho { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
