//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTraQuayHang
    {
        public PhieuTraQuayHang()
        {
            this.CT_PhieuTraQuayHang = new HashSet<CT_PhieuTraQuayHang>();
        }
    
        public System.Guid PhieuTraQuayHangId { get; set; }
        public long NhanVienId { get; set; }
        public long QuayHangId { get; set; }
        public long KhoId { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<long> NguoiChinhSuaId { get; set; }
    
        public virtual ICollection<CT_PhieuTraQuayHang> CT_PhieuTraQuayHang { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual QuayHang QuayHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
