//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuayHang
    {
        public QuayHang()
        {
            this.HangHoas = new HashSet<HangHoa>();
            this.PhieuTraQuayHangs = new HashSet<PhieuTraQuayHang>();
        }
    
        public long Id { get; set; }
        public string TenQuay { get; set; }
        public Nullable<bool> HoatDong { get; set; }
    
        public virtual ICollection<HangHoa> HangHoas { get; set; }
        public virtual ICollection<PhieuTraQuayHang> PhieuTraQuayHangs { get; set; }
    }
}
