//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenNhanVien
    {
        public long Id { get; set; }
        public long QuyenId { get; set; }
        public long NhanVienId { get; set; }
        public bool HoatDong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
