//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen
    {
        public Quyen()
        {
            this.QuyenNhanViens = new HashSet<QuyenNhanVien>();
        }
    
        public long Id { get; set; }
        public string Quyen1 { get; set; }
    
        public virtual ICollection<QuyenNhanVien> QuyenNhanViens { get; set; }
    }
}
