CREATE TABLE [dbo].[ChucVu]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [TenChucVu] NVARCHAR(100) NOT NULL,
	[NgayTao] DATETIME2 NULL DEFAULT SYSDATETIME(), 
    [NguoiTaoId] BIGINT NULL, 
    [NgayChinhSua] DATETIME2 NULL DEFAULT SYSDATETIME(), 
    [NguoiChinhSuaId] BIGINT NULL, 
    [HoatDong] BIT NULL DEFAULT 1, 
     CONSTRAINT [FK_ChucVu_NguoiTao] FOREIGN KEY ([NguoiTaoId]) REFERENCES [NhanVien]([Id]),
	 CONSTRAINT [FK_ChucVu_NguoiChinhSua] FOREIGN KEY ([NguoiChinhSuaId]) REFERENCES [NhanVien]([Id])
	
)
