CREATE TABLE [dbo].[CT_DonHang]
(
	[DonHangId] UNIQUEIDENTIFIER NOT NULL , 
	[HangHoaId] BIGINT NOT NULL,
	[SoLuong] INT NOT NULL DEFAULT 0,
	[DonGia] DECIMAL(18,0) NOT NULL,
	PRIMARY KEY([DonHangId], [HangHoaId]),
	CONSTRAINT [FK_CTDonHang_DonHang] FOREIGN KEY ([DonHangId]) REFERENCES [DonHang]([DonHangId]),
	CONSTRAINT [FK_CTDonHang_HangHoa] FOREIGN KEY ([HangHoaId]) REFERENCES [HangHoa]([Id])
)
