CREATE TABLE [dbo].[NhaCungCap]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [TenNhaCungCap] NVARCHAR(255) NOT NULL, 
    [TenCongTy] NVARCHAR(255) NOT NULL, 
    [DiaChi] NVARCHAR(255) NOT NULL, 
    [SoDienThoai] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NULL,
	[NgayTao] DATETIME2 NULL DEFAULT SYSDATETIME(), 
    [NguoiTaoId] BIGINT NULL,
    [NgayChinhSua] DATETIME2 NULL DEFAULT SYSDATETIME(), 
    [NguoiChinhSuaId] BIGINT NULL,
    [HoatDong] BIT NULL DEFAULT 1,
	CONSTRAINT [FK_NhaCungCap_NguoiTao] FOREIGN KEY ([NguoiTaoId]) REFERENCES [NhanVien]([Id]),
	CONSTRAINT [FK_NhaCungCap_NguoiChinhSua] FOREIGN KEY ([NguoiChinhSuaId]) REFERENCES [NhanVien]([Id])
)
